[package]
name = "birthday_greetings"
version = "0.1.0"
authors = ["Michele d'Amico <michele.damico@rcslab.it>"]
edition = "2018"

[dependencies]
chrono = "*"
csv = "*"
lettre = "0.9"
lettre_email = "0.9"

[dev-dependencies]
temp_testdir = "0.2"
json = "*"
rstest = {path = "../rstest"}
